<?xml  version="1.0" encoding="UTF-8"?>
<!DOCTYPE plist PUBLIC "-//Apple Computer//DTD PLIST 1.0//EN"   "http://www.apple.com/DTDs/PropertyList-1.0.dtd">
<plist version="1.0" >
<!-- Generated via Iro -->
<dict>
  <key>fileTypes</key>
  <array>
    <string>model</string>
    <string>domain</string>
   </array>
  <key>name</key>
  <string>idealingua1</string>
  <key>patterns</key>
  <array>
    <dict>
      <key>include</key>
      <string>#main</string>
    </dict>
   </array>
  <key>scopeName</key>
  <string>source.idealingua1</string>
  <key>uuid</key>
  <string></string>
  <key>repository</key>
  <dict>
    <key>main</key>
    <dict>
      <key>patterns</key>
      <array>
        <dict>
          <key>include</key>
          <string>#package</string>
        </dict>
        <dict>
          <key>include</key>
          <string>#import</string>
        </dict>
        <dict>
          <key>include</key>
          <string>#include</string>
        </dict>
        <dict>
          <key>include</key>
          <string>#keyword</string>
        </dict>
        <dict>
          <key>include</key>
          <string>#type</string>
        </dict>
        <dict>
          <key>include</key>
          <string>#user_type</string>
        </dict>
        <dict>
          <key>include</key>
          <string>#attribute</string>
        </dict>
        <dict>
          <key>include</key>
          <string>#punctuation</string>
        </dict>
        <dict>
          <key>include</key>
          <string>#block</string>
        </dict>
        <dict>
          <key>include</key>
          <string>#comments</string>
        </dict>
        <dict>
          <key>include</key>
          <string>#whitespace</string>
        </dict>
       </array>
    </dict>
    <key>attribute</key>
    <dict>
      <key>patterns</key>
      <array>
        <dict>
          <key>match</key>
          <string>(@[a-zA-Z0-9_]*)</string>
          <key>name</key>
          <string>markup.idealingua1</string>
        </dict>
       </array>
    </dict>
    <key>block</key>
    <dict>
      <key>patterns</key>
      <array>
        <dict>
          <key>begin</key>
          <string>([\s\{])</string>
          <key>beginCaptures</key>
          <dict>
            <key>1</key>
            <dict>
              <key>name</key>
              <string>punctuation.idealingua1</string>
            </dict>
          </dict>
          <key>patterns</key>
          <array>
            <dict>
              <key>include</key>
              <string>#uid_block</string>
            </dict>
           </array>
          <key>end</key>
          <string>(\})</string>
          <key>endCaptures</key>
          <dict>
            <key>1</key>
            <dict>
              <key>name</key>
              <string>punctuation.idealingua1</string>
            </dict>
          </dict>
        </dict>
       </array>
    </dict>
    <key>comments</key>
    <dict>
      <key>patterns</key>
      <array>
        <dict>
          <key>match</key>
          <string>(\s?//.*)</string>
          <key>name</key>
          <string>comment.idealingua1</string>
        </dict>
        <dict>
          <key>begin</key>
          <string>(/\*)</string>
          <key>beginCaptures</key>
          <dict>
            <key>1</key>
            <dict>
              <key>name</key>
              <string>comment.idealingua1</string>
            </dict>
          </dict>
          <key>patterns</key>
          <array>
            <dict>
              <key>include</key>
              <string>#uid_multilinecomment</string>
            </dict>
           </array>
          <key>end</key>
          <string>(.*?\*/)</string>
          <key>endCaptures</key>
          <dict>
            <key>1</key>
            <dict>
              <key>name</key>
              <string>comment.idealingua1</string>
            </dict>
          </dict>
        </dict>
       </array>
    </dict>
    <key>field</key>
    <dict>
      <key>patterns</key>
      <array>
        <dict>
          <key>match</key>
          <string>(\s?\b[a-zA-Z0-9_]*)</string>
          <key>name</key>
          <string>variable.idealingua1</string>
        </dict>
       </array>
    </dict>
    <key>import</key>
    <dict>
      <key>patterns</key>
      <array>
        <dict>
          <key>begin</key>
          <string>(import[\s\x{002a}])</string>
          <key>beginCaptures</key>
          <dict>
            <key>1</key>
            <dict>
              <key>name</key>
              <string>keyword.other.unit.idealingua1</string>
            </dict>
          </dict>
          <key>contentName</key>
          <string>entity.name.class.idealingua1</string>
          <key>end</key>
          <string>((\{)|(\s?)*(?!.))</string>
          <key>endCaptures</key>
          <dict>
            <key>1</key>
            <dict>
              <key>name</key>
              <string>punctuation.idealingua1</string>
            </dict>
          </dict>
        </dict>
       </array>
    </dict>
    <key>include</key>
    <dict>
      <key>patterns</key>
      <array>
        <dict>
          <key>begin</key>
          <string>(include[\s\x{002a}])</string>
          <key>beginCaptures</key>
          <dict>
            <key>1</key>
            <dict>
              <key>name</key>
              <string>keyword.other.unit.idealingua1</string>
            </dict>
          </dict>
          <key>patterns</key>
          <array>
            <dict>
              <key>include</key>
              <string>#uid_include</string>
            </dict>
           </array>
          <key>end</key>
          <string>(^(?=.{0,1})(?:|))</string>
          <key>endCaptures</key>
          <dict>
            <key>1</key>
            <dict>
              <key>name</key>
              <string>entity.name.idealingua1</string>
            </dict>
          </dict>
        </dict>
       </array>
    </dict>
    <key>include__2</key>
    <dict>
      <key>patterns</key>
      <array>
       </array>
    </dict>
    <key>keyword</key>
    <dict>
      <key>patterns</key>
      <array>
        <dict>
          <key>match</key>
          <string>(\s?(id|enum|adt|const|data|service|mixin|interface|def)(?!([a-zA-Z0-9_]|\s:|:)))</string>
          <key>name</key>
          <string>keyword.other.unit.idealingua1</string>
        </dict>
       </array>
    </dict>
    <key>numeric</key>
    <dict>
      <key>patterns</key>
      <array>
        <dict>
          <key>match</key>
          <string>(\s?\b\d+)</string>
          <key>name</key>
          <string>constant.numeric.idealingua1</string>
        </dict>
       </array>
    </dict>
    <key>package</key>
    <dict>
      <key>patterns</key>
      <array>
        <dict>
          <key>begin</key>
          <string>((package|domain)[\s\x{002a}])</string>
          <key>beginCaptures</key>
          <dict>
            <key>1</key>
            <dict>
              <key>name</key>
              <string>entity.name.idealingua1</string>
            </dict>
          </dict>
          <key>contentName</key>
          <string>entity.name.class.idealingua1</string>
          <key>end</key>
          <string>(\s)</string>
          <key>endCaptures</key>
          <dict>
            <key>1</key>
            <dict>
              <key>name</key>
              <string>text.idealingua1</string>
            </dict>
          </dict>
        </dict>
       </array>
    </dict>
    <key>params</key>
    <dict>
      <key>patterns</key>
      <array>
        <dict>
          <key>begin</key>
          <string>(\s?\()</string>
          <key>beginCaptures</key>
          <dict>
            <key>1</key>
            <dict>
              <key>name</key>
              <string>punctuation.idealingua1</string>
            </dict>
          </dict>
          <key>patterns</key>
          <array>
            <dict>
              <key>include</key>
              <string>#uid_params</string>
            </dict>
           </array>
          <key>end</key>
          <string>(\))</string>
          <key>endCaptures</key>
          <dict>
            <key>1</key>
            <dict>
              <key>name</key>
              <string>punctuation.idealingua1</string>
            </dict>
          </dict>
        </dict>
       </array>
    </dict>
    <key>punctuation</key>
    <dict>
      <key>patterns</key>
      <array>
        <dict>
          <key>match</key>
          <string>(\s?[\x{0021}\x{007c}\x{002b}\-\x{002c}.\x{007b}\x{007d}\[\]\x{003d}\x{003a}\x{003e}\x{0026}])</string>
          <key>name</key>
          <string>punctuation.idealingua1</string>
        </dict>
       </array>
    </dict>
    <key>quoted_text</key>
    <dict>
      <key>patterns</key>
      <array>
        <dict>
          <key>begin</key>
          <string>(&quot;)</string>
          <key>beginCaptures</key>
          <dict>
            <key>1</key>
            <dict>
              <key>name</key>
              <string>punctuation.idealingua1</string>
            </dict>
          </dict>
          <key>patterns</key>
          <array>
            <dict>
              <key>include</key>
              <string>#quoted_text__1</string>
            </dict>
           </array>
          <key>end</key>
          <string>(&quot;)</string>
          <key>endCaptures</key>
          <dict>
            <key>1</key>
            <dict>
              <key>name</key>
              <string>punctuation.idealingua1</string>
            </dict>
          </dict>
        </dict>
       </array>
    </dict>
    <key>quoted_text__1</key>
    <dict>
      <key>patterns</key>
      <array>
        <dict>
          <key>match</key>
          <string>(\\(?:\\|&quot;))</string>
          <key>name</key>
          <string>string.regexp.idealingua1</string>
        </dict>
        <dict>
          <key>match</key>
          <string>([^\x{0022}\x{005c}]+)</string>
          <key>name</key>
          <string>string.idealingua1</string>
        </dict>
       </array>
    </dict>
    <key>type</key>
    <dict>
      <key>patterns</key>
      <array>
        <dict>
          <key>match</key>
          <string>(\s?(bit|boolean|bool|string|str|i08|byte|int8|bigint|big|i16|short|int16|i32|int|int32|i64|long|int64|u08|ubyte|uint8|u16|ushort|uint16|u32|uint32|uint|u64|ulong|uint64|f32|flt|float|f64|dbl|double|uid|uuid|blob|blb|bytes|tsl|datetimel|tso|datetimeo|tsu|datetimeu|time|date|error|err|any|lst|list|set|opt|option|map|dict|either|alt)(?!([a-zA-Z0-9_]|\s?:)))</string>
          <key>name</key>
          <string>keyword.idealingua1</string>
        </dict>
       </array>
    </dict>
    <key>uid_block</key>
    <dict>
      <key>patterns</key>
      <array>
        <dict>
          <key>include</key>
          <string>#comments</string>
        </dict>
        <dict>
          <key>include</key>
          <string>#punctuation</string>
        </dict>
        <dict>
          <key>include</key>
          <string>#numeric</string>
        </dict>
        <dict>
          <key>include</key>
          <string>#quoted_text</string>
        </dict>
        <dict>
          <key>include</key>
          <string>#keyword</string>
        </dict>
        <dict>
          <key>include</key>
          <string>#type</string>
        </dict>
        <dict>
          <key>include</key>
          <string>#user_field_type</string>
        </dict>
        <dict>
          <key>include</key>
          <string>#attribute</string>
        </dict>
        <dict>
          <key>include</key>
          <string>#params</string>
        </dict>
        <dict>
          <key>include</key>
          <string>#field</string>
        </dict>
        <dict>
          <key>include</key>
          <string>#params</string>
        </dict>
        <dict>
          <key>include</key>
          <string>#whitespace</string>
        </dict>
       </array>
    </dict>
    <key>uid_import</key>
    <dict>
      <key>patterns</key>
      <array>
       </array>
    </dict>
    <key>uid_include</key>
    <dict>
      <key>patterns</key>
      <array>
        <dict>
          <key>begin</key>
          <string>(\&quot;)</string>
          <key>beginCaptures</key>
          <dict>
            <key>1</key>
            <dict>
              <key>name</key>
              <string>punctuation.idealingua1</string>
            </dict>
          </dict>
          <key>contentName</key>
          <string>string.idealingua1</string>
          <key>end</key>
          <string>(\&quot;)</string>
          <key>endCaptures</key>
          <dict>
            <key>1</key>
            <dict>
              <key>name</key>
              <string>punctuation.idealingua1</string>
            </dict>
          </dict>
        </dict>
        <dict>
          <key>include</key>
          <string>#comments</string>
        </dict>
       </array>
    </dict>
    <key>uid_multilinecomment</key>
    <dict>
      <key>patterns</key>
      <array>
        <dict>
          <key>match</key>
          <string>(@[a-zA-Z0-9_]*)</string>
          <key>name</key>
          <string>variable.idealingua1</string>
        </dict>
        <dict>
          <key>match</key>
          <string>(\w|[\x{0023}\x{003f}\x{005c}\x{0024}\x{003a}\x{002f}.\x{002c}\x{0027}\x{0060}\-\x{003d}\(\)\[\]\{\}\*\x{003c}\x{003e}\x{0022}\x{201d}\x{2019}])</string>
          <key>name</key>
          <string>comment.idealingua1</string>
        </dict>
       </array>
    </dict>
    <key>uid_package</key>
    <dict>
      <key>patterns</key>
      <array>
       </array>
    </dict>
    <key>uid_params</key>
    <dict>
      <key>patterns</key>
      <array>
        <dict>
          <key>include</key>
          <string>#comments</string>
        </dict>
        <dict>
          <key>include</key>
          <string>#quoted_text</string>
        </dict>
        <dict>
          <key>include</key>
          <string>#punctuation</string>
        </dict>
        <dict>
          <key>include</key>
          <string>#keyword</string>
        </dict>
        <dict>
          <key>include</key>
          <string>#type</string>
        </dict>
        <dict>
          <key>include</key>
          <string>#user_field_type</string>
        </dict>
        <dict>
          <key>include</key>
          <string>#field</string>
        </dict>
        <dict>
          <key>include</key>
          <string>#whitespace</string>
        </dict>
       </array>
    </dict>
    <key>user_field_type</key>
    <dict>
      <key>patterns</key>
      <array>
        <dict>
          <key>match</key>
          <string>(\s?[a-zA-Z0-9_]*((?=\s?(\]|,|//|!|\)|\|))|((\s?)*(?!.))))</string>
          <key>name</key>
          <string>support.type.idealingua1</string>
        </dict>
       </array>
    </dict>
    <key>user_type</key>
    <dict>
      <key>patterns</key>
      <array>
        <dict>
          <key>match</key>
          <string>(\s?\b[a-zA-Z0-9_]*)</string>
          <key>name</key>
          <string>support.type.idealingua1</string>
        </dict>
       </array>
    </dict>
    <key>whitespace</key>
    <dict>
      <key>patterns</key>
      <array>
        <dict>
          <key>match</key>
          <string>(\s+)</string>
          <key>name</key>
          <string>text.idealingua1</string>
        </dict>
       </array>
    </dict>
  </dict>
</dict>
</plist>
